### ISSUE TITLE
请问这个支持ppt、图片、视频插入功能什么时候可以发布

### ISSUE THREAD

**Issue by shiguanghuxian** [netless-io/fastboard_flutter#1]
完整的window-manager功能什么时候可以使用，最近2个月内可以使用嘛

**Comment by aderan** [comment]
计划在六月底 flutter 版本会与 Android/iOS 版本保持接口同步。
By the end of June, the flutter version will be in sync with the Android/iOS version.

**Comment by shiguanghuxian** [comment]
好的，谢谢
