### ISSUE TITLE
APPID issue

### ISSUE THREAD

**Issue by Muhammad-Ullah** [netless-io/fastboard_flutter#2]
Where can I get APP_ID?

**Comment by aderan** [comment]
@Muhammad-Ullah fastboard-flutter is a library for Agora Interactive Whiteboard. To get APP_ID, you need a valid [agora account](https://docs.agora.io/en/interactive-whiteboard/reference/manage-agora-account?platform=android#sign-up-and-log-in), and then [enable whiteboard support](https://docs.agora.io/en/interactive-whiteboard/develop/enable-whiteboard?platform=android).
